name: {{project_name.snakeCase()}}
description: {{{description}}}
version: 1.0.0+1
{{^publishable}}publish_to: none{{/publishable}}{{#workspace}}
resolution: workspace{{/workspace}}

environment:
  sdk: ^3.12.0
  flutter: ^3.44.0

dependencies:
  bloc: ^9.2.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  bloc_lint: ^0.4.2
  bloc_test: ^10.0.0
  bloc_tools: ^0.1.0-dev.24
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.5
  very_good_analysis: ^10.3.0

flutter:
  generate: true
  uses-material-design: true
