// Copyright (c) 2025, Very Good Ventures
// https://verygood.ventures

{{#use_build_hooks}}
import 'dart:ffi';

/// Native bindings for FFI functions.
///
/// This file demonstrates how to use the @Native annotation to reference
/// assets generated by build hooks. The asset ID defaults to the library URI,
/// which matches the asset generated by the build hook.
///
/// For more information, see:
/// https://dart.dev/tools/hooks#reference-assets

/// Example native function that adds two integers.
///
/// This function is implemented in native C code (src/native_example.c)
/// and compiled by the build hook. The @Native annotation automatically
/// resolves to the asset generated by the hook.
///
/// Example usage:
/// ```dart
/// import 'package:{{project_name.snakeCase()}}/{{project_name.snakeCase()}}.dart';
///
/// void main() {
///   final result = add(24, 18);
///   print('24 + 18 = $result'); // Prints: 24 + 18 = 42
/// }
/// ```
@Native<Int32 Function(Int32, Int32)>()
external int add(int a, int b);
{{/use_build_hooks}}
