name: very_good_dart_cli_hooks

environment:
  sdk: "^3.3.0"

dependencies:
  mason: ">=0.1.0-dev.52 <0.1.0"
  meta: ^1.12.0

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^5.1.0
