name: very_good_dart_cli_hooks

environment:
  sdk: "^3.1.0"

dependencies:
  mason: ">=0.1.0-dev.51 <0.1.0"
  meta: ^1.11.0

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
