name: {{project_name.snakeCase()}}
description: {{{description}}}
version: 0.1.0+1
{{^publishable}}publish_to: none{{/publishable}}

environment:
  sdk: ^3.11.0
  flutter: ^3.41.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.5
  very_good_analysis: ^10.2.0

flutter:
  fonts:
    - family: CustomFont
      fonts:
        - asset: assets/fonts/CustomFont-Light.ttf
          weight: 300
        - asset: assets/fonts/CustomFont-Regular.ttf
          weight: 400
        - asset: assets/fonts/CustomFont-Medium.ttf
          weight: 500
        - asset: assets/fonts/CustomFont-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/CustomFont-Bold.ttf
          weight: 700
