/// Version information about the template.
///
/// [$templateVersion] is automatically updated by release-please on each
/// release. The remaining constants are manually maintained and should be
/// updated when the template requires to be updated.
library;

/// The version of the template.
const $templateVersion = '1.3.2'; // x-release-please-version

/// The Flutter version associated with the template version.
const $flutterVersion = '3.41.1';

/// The minimum Dart version required by the template.
///
/// This should match with the Dart version associated with the Flutter version
/// [$flutterVersion].
///
/// See also:
///
/// * [Flutter SDK archive](https://docs.flutter.dev/release/archive)
const $minDartVersion = '3.11.0';

/// The available platforms that can be generated by the template.
const $availablePlatforms = [
  'android',
  'ios',
  'macos',
  'linux',
  'web',
  'windows',
];

/// The platforms that use Pigeon for native bindings.
///
/// Web is excluded because it does not use native code and therefore does not
/// require Pigeon code generation.
const $pigeonPlatforms = [
  'android',
  'ios',
  'macos',
  'linux',
  'windows',
];
