/// Version information about the template.
///
/// This file is not automatically generated. It is manually maintained and
/// should be updated when the template requires to be updated.
library;

/// The version of the template.
const $templateVersion = '1.0.0';

/// The Flutter version associated with the template version.
const $flutterVersion = '3.35.0';

/// The minimum Dart version required by the template.
///
/// This should match with the Dart version associated with the Flutter version
/// [$flutterVersion].
///
/// See also:
///
/// * [Flutter SDK archive](https://docs.flutter.dev/release/archive)
const $minDartVersion = '3.9.0';

/// The available platforms that can be generated by the template.
const $availablePlatforms = [
  'android',
  'ios',
  'macos',
  'linux',
  'web',
  'windows',
];
