name: e2e
description: Very Good Wear OS App's end-to-end testing package.
publish_to: none

environment:
  sdk: "^3.3.0"

dev_dependencies:
  mason: ^0.1.0-dev.52
  path: ^1.9.0
  test: ^1.25.2
  very_good_analysis: ^5.1.0
