name: {{project_name.snakeCase()}}

concurrency:
  group: ${{#mustacheCase}}github.workflow{{/mustacheCase}}-${{#mustacheCase}}github.ref{{/mustacheCase}}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - ".github/workflows/{{project_name.snakeCase()}}.yaml"
      - "{{project_name.snakeCase()}}/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/{{project_name.snakeCase()}}.yaml"
      - "{{project_name.snakeCase()}}/**"

jobs:
  spell-check:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/spell_check.yml@v1
    with:
      includes: |
        **/*.md
        !brick/**/*.md
        .*/**/*.md
      modified_files_only: false

  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_version: {{{flutterVersion}}}
      working_directory: {{project_name.snakeCase()}}
{{#publishable}}
  pana:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/pana.yml@v1
{{/publishable}}
{{#android}}
  android:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: {{project_name.snakeCase()}}/example

    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-java@v6
        with:
          distribution: "temurin"
          java-version: "17"

      - uses: subosito/flutter-action@v2

      - name: Install Fluttium
        run: flutter pub global activate fluttium_cli

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: AVD Cache
        uses: actions/cache@v6
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-29-x86_64

      - name: Cache AVD Snapshot
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: E2E Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86_64
          script: fluttium test flows/test_platform_name.yaml -d android
          working-directory: {{project_name.snakeCase()}}/example
{{/android}}
{{#ios}}
  ios:
    runs-on: macos-latest

    defaults:
      run:
        working-directory: {{project_name.snakeCase()}}/example

    steps:
      - uses: actions/checkout@v7

      - uses: subosito/flutter-action@v2

      - name: Install Fluttium
        run: flutter pub global activate fluttium_cli

      - name: Start Simulator
        # Start an iPhone simulator
        run: |
          UDID=$(xcrun xctrace list devices | grep "^iPhone" | awk '{gsub(/[()]/,""); print $NF}' | head -n 1)
          echo $UDID
          xcrun simctl boot "${UDID:?No Simulator with this name found}"

      - name: E2E Tests
        run: fluttium test flows/test_platform_name.yaml -d iPhone
{{/ios}}
{{#linux}}
  linux:
    runs-on: ubuntu-latest
    if: false # todo(renancaraujo): https://github.com/wolfenrain/fluttium/issues/345
    defaults:
      run:
        working-directory: {{project_name.snakeCase()}}/example

    steps:
      - uses: actions/checkout@v7

      - uses: subosito/flutter-action@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libx11-dev pkg-config cmake ninja-build libblkid-dev liblzma-dev

      - name: Install Fluttium
        run: flutter pub global activate fluttium_cli

      - name: E2E Tests
        run: xvfb-run fluttium test flows/test_platform_name.yaml -d linux
{{/linux}}
{{#macos}}
  macos:
    runs-on: macos-latest

    defaults:
      run:
        working-directory: {{project_name.snakeCase()}}/example

    steps:
      - uses: actions/checkout@v7

      - uses: subosito/flutter-action@v2

      - name: Install Fluttium
        run: flutter pub global activate fluttium_cli

      - name: E2E Tests
        run: fluttium test flows/test_platform_name.yaml -d macos
{{/macos}}
{{#web}}
  web:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: {{project_name.snakeCase()}}/example

    steps:
      - uses: actions/checkout@v7

      - uses: subosito/flutter-action@v2

      - name: Install Fluttium
        run: flutter pub global activate fluttium_cli

      - name: E2E Tests
        run: xvfb-run fluttium test flows/test_platform_name.yaml -d chrome
{{/web}}
{{#windows}}
  windows:
    runs-on: windows-latest

    defaults:
      run:
        working-directory: {{project_name.snakeCase()}}/example

    steps:
      - uses: actions/checkout@v7

      - uses: subosito/flutter-action@v2

      - name: Install Fluttium
        run: flutter pub global activate fluttium_cli

      - name: E2E Tests
        run: fluttium test flows/test_platform_name.yaml -d windows
{{/windows}}
{{#android}}
  integration_test_android:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: {{project_name.snakeCase()}}/example

    steps:
      - uses: actions/checkout@v7

      - uses: subosito/flutter-action@v2

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: AVD Cache
        uses: actions/cache@v6
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-29-x86_64

      - name: Cache AVD Snapshot
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: E2E Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86_64
          script: flutter test integration_test -d emulator-5554
          working-directory: {{project_name.snakeCase()}}/example
{{/android}}
{{#supports_ios}}
  integration_test_ios:
    runs-on: macos-latest

    defaults:
      run:
        working-directory: {{project_name.snakeCase()}}/example

    steps:
      - uses: actions/checkout@v7

      - uses: subosito/flutter-action@v2

      - name: Start Simulator
        # Start an iPhone simulator
        run: |
          UDID=$(xcrun xctrace list devices | grep "^iPhone" | awk '{gsub(/[()]/,""); print $NF}' | head -n 1)
          echo "$UDID"
          xcrun simctl bootstatus "${UDID:?No Simulator with this name found}" -b

      - name: E2E Tests
        run: flutter test integration_test -d iPhone
{{/supports_ios}}
{{#supports_macos}}
  integration_test_macos:
    runs-on: macos-latest

    defaults:
      run:
        working-directory: {{project_name.snakeCase()}}/example

    steps:
      - uses: actions/checkout@v7

      - uses: subosito/flutter-action@v2

      - name: E2E Tests
        run: flutter test integration_test -d macos
{{/supports_macos}}
{{#web}}
  integration_test_web:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: {{project_name.snakeCase()}}/example

    steps:
      - uses: actions/checkout@v7

      - uses: subosito/flutter-action@v2

      - name: Start ChromeDriver
        # Uses the ChromeDriver that matches the runner's preinstalled Chrome.
        run: |
          "$CHROMEWEBDRIVER/chromedriver" --port=4444 &

      - name: E2E Tests
        run: flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart -d web-server
{{/web}}
{{#windows}}
  integration_test_windows:
    runs-on: windows-latest

    defaults:
      run:
        working-directory: {{project_name.snakeCase()}}/example

    steps:
      - uses: actions/checkout@v7

      - uses: subosito/flutter-action@v2

      - name: E2E Tests
        run: flutter test integration_test -d windows
{{/windows}}
{{#linux}}
  integration_test_linux:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: {{project_name.snakeCase()}}/example

    steps:
      - uses: actions/checkout@v7

      - uses: subosito/flutter-action@v2

      - name: Install Dependencies
        # https://docs.flutter.dev/platform-integration/linux/setup
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev libstdc++-12-dev

      - name: E2E Tests
        run: xvfb-run flutter test integration_test -d linux
{{/linux}}
{{#android}}
  patrol_android:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: {{project_name.snakeCase()}}/example

    steps:
      - uses: actions/checkout@v7

      - uses: subosito/flutter-action@v2

      - name: Install Patrol CLI
        run: flutter pub global activate patrol_cli

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: AVD Cache
        uses: actions/cache@v6
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-29-x86_64

      - name: Cache AVD Snapshot
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: E2E Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86_64
          script: patrol test -t patrol_test/app_test.dart -d emulator-5554
          working-directory: {{project_name.snakeCase()}}/example
{{/android}}
{{#web}}
  patrol_web:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: {{project_name.snakeCase()}}/example

    steps:
      - uses: actions/checkout@v7

      - uses: subosito/flutter-action@v2

      - name: Install Patrol CLI
        run: flutter pub global activate patrol_cli

      - name: E2E Tests
        run: patrol test -t patrol_test/app_test.dart -d chrome --web-headless
{{/web}}
