/// Builds [SidebarGroup]s automatically from the filesystem, mirroring the
/// autogenerated sidebar behavior of Docusaurus
/// (`{ type: 'autogenerated', dirName: '.' }`).
///
/// This only runs on the server during pre-rendering (static mode), so
/// `dart:io` is safe to use here. It must never be imported from
/// `main.client.dart` or any `@client` component.
library;

import 'dart:io';

import 'package:jaspr_content/components/sidebar.dart';

/// Scans [directory] for markdown files and builds sidebar groups.
///
/// - Files directly inside [directory] form the first (untitled) group.
/// - Each immediate subdirectory becomes a titled group (title-cased name),
///   containing all markdown files below it (flattened — jaspr_content's
///   sidebar supports a single level of nesting).
/// - Entries are ordered by the `sidebar_position` frontmatter key when
///   present, then alphabetically by title.
/// - Entry text comes from the `title` frontmatter key, falling back to the
///   first `# ` heading, then to the title-cased file name.
List<SidebarGroup> buildSidebarGroups({
  String directory = 'content/docs',
  String urlPrefix = '/docs',
}) {
  final root = Directory(directory);
  if (!root.existsSync()) return [];

  final rootEntries = <_SidebarEntry>[];
  final groups = <SidebarGroup>[];

  final children = root.listSync()..sort((a, b) => a.path.compareTo(b.path));

  for (final child in children) {
    if (child is File && _isMarkdown(child.path)) {
      rootEntries.add(_entryFor(child, root, urlPrefix));
    }
  }

  if (rootEntries.isNotEmpty) {
    groups.add(SidebarGroup(links: _sortedLinks(rootEntries)));
  }

  for (final child in children) {
    if (child is! Directory) continue;
    final dirName = child.uri.pathSegments.lastWhere((s) => s.isNotEmpty);
    if (dirName.startsWith('_') || dirName.startsWith('.')) continue;

    final entries = child
        .listSync(recursive: true)
        .whereType<File>()
        .where((f) => _isMarkdown(f.path))
        .map((f) => _entryFor(f, root, urlPrefix))
        .toList();

    if (entries.isNotEmpty) {
      groups.add(
        SidebarGroup(title: _titleCase(dirName), links: _sortedLinks(entries)),
      );
    }
  }

  return groups;
}

class _SidebarEntry {
  const _SidebarEntry({
    required this.title,
    required this.href,
    required this.position,
  });

  final String title;
  final String href;
  final int position;
}

final _markdownExtension = RegExp(r'\.mdx?$');
final _firstHeadingPattern = RegExp(r'^# (.+)$', multiLine: true);
final _wordSeparator = RegExp('[_-]');

bool _isMarkdown(String path) => _markdownExtension.hasMatch(path);

List<SidebarLink> _sortedLinks(List<_SidebarEntry> entries) {
  entries.sort((a, b) {
    final byPosition = a.position.compareTo(b.position);
    return byPosition != 0 ? byPosition : a.title.compareTo(b.title);
  });
  return [
    for (final entry in entries)
      SidebarLink(text: entry.title, href: entry.href),
  ];
}

_SidebarEntry _entryFor(File file, Directory root, String urlPrefix) {
  final (data: frontmatter, :body) = _readFrontmatter(file.readAsStringSync());

  var relative = file.path
      .substring(root.path.length)
      .replaceAll(r'\', '/')
      .replaceFirst(_markdownExtension, '');
  if (relative.startsWith('/')) relative = relative.substring(1);
  if (relative == 'index' || relative.endsWith('/index')) {
    relative = relative.substring(0, relative.length - 'index'.length);
    if (relative.endsWith('/')) {
      relative = relative.substring(0, relative.length - 1);
    }
  }

  final fileName = relative.split('/').last;
  final title =
      frontmatter['title'] ?? _firstHeading(body) ?? _titleCase(fileName);
  // Entries with no `sidebar_position` sort after positioned ones.
  final position =
      int.tryParse(frontmatter['sidebar_position'] ?? '') ?? 1 << 30;

  final href = relative.isEmpty ? urlPrefix : '$urlPrefix/$relative';
  return _SidebarEntry(title: title, href: href, position: position);
}

/// Reads the top-level frontmatter keys of [content] plus the body below it.
///
/// Only unnested scalar values are recognized, which is all the sidebar needs
/// (`title` and `sidebar_position`). Quoted values are unwrapped. Reading
/// these two keys here keeps the template free of a YAML dependency;
/// jaspr_content still does the full YAML parse when it renders the page.
({Map<String, String> data, String body}) _readFrontmatter(String content) {
  final lines = content.split('\n');
  if (lines.first.trim() != '---') return (data: const {}, body: content);

  final closing = lines.indexWhere((line) => line.trim() == '---', 1);
  if (closing == -1) return (data: const {}, body: content);

  final data = <String, String>{};
  for (final line in lines.getRange(1, closing)) {
    final trimmed = line.trim();
    if (trimmed.isEmpty || trimmed.startsWith('#')) continue;

    final separator = trimmed.indexOf(':');
    if (separator == -1) continue;

    final key = trimmed.substring(0, separator).trim();
    final value = _unquote(trimmed.substring(separator + 1).trim());
    if (key.isNotEmpty && value.isNotEmpty) data[key] = value;
  }

  return (data: data, body: lines.skip(closing + 1).join('\n'));
}

String _unquote(String value) {
  for (final quote in const ['"', "'"]) {
    if (value.length >= 2 && value.startsWith(quote) && value.endsWith(quote)) {
      return value.substring(1, value.length - 1);
    }
  }
  return value;
}

String? _firstHeading(String content) {
  final match = _firstHeadingPattern.firstMatch(content);
  return match?.group(1)?.trim();
}

String _titleCase(String value) => value
    .split(_wordSeparator)
    .where((word) => word.isNotEmpty)
    .map((word) => word[0].toUpperCase() + word.substring(1))
    .join(' ');
