name: check_platform_name
description: A custom action for Fluttium.
version: 0.1.0+1

environment:
  sdk: "{{{dartSdkVersionBounds}}}"

dependencies:
  flutter:
    sdk: flutter
  fluttium: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0
