name: very_good_docs_site_hooks

on:
  pull_request:
    paths:
      - ".github/workflows/very_good_docs_site_hooks.yaml"
      - "very_good_docs_site/hooks/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/very_good_docs_site_hooks.yaml"
      - "very_good_docs_site/hooks/**"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@v1.19.2
    with:
      dart_sdk: "3.11.0"
      report_on: "pre_gen.dart"
      run_bloc_lint: false
      working_directory: "very_good_docs_site/hooks"
      analyze_directories: "test"
