name: very_good_dart_cli

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    paths:
      - .github/workflows/very_good_dart_cli.yaml
      - "very_good_dart_cli/**"
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/very_good_dart_cli.yaml
      - "very_good_dart_cli/**"
    branches:
      - main

jobs:
  brick:
    defaults:
      run:
        working-directory: very_good_dart_cli/

    runs-on: ubuntu-latest

    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v6

      - name: 🎯 Setup Dart
        uses: dart-lang/setup-dart@v1.7.2
        with:
          sdk: "3.11.0"

      - name: 🧱 Mason Make
        run: |
          dart pub global activate mason_cli 0.1.3
          dart pub global activate very_good_cli 1.1.0
          mason get
          mason make very_good_dart_cli -c config.json --on-conflict overwrite -o very_good_dart_cli_output

      - name: 📦 Install Dependencies
        run: very_good packages get very_good_dart_cli_output

      - name: ✨ Check Formatting
        run: dart format --set-exit-if-changed very_good_dart_cli_output

      - name: 🕵️ Analyze
        run: dart analyze --fatal-infos --fatal-warnings very_good_dart_cli_output

      - name: 🧪 Run Tests
        run: |
          cd very_good_dart_cli_output
          very_good dart test -j 4 --optimization --min-coverage 100 --test-randomize-ordering-seed random
